<a href="https://colab.research.google.com/github/So47/Pytorch_notebooks/blob/main/pytorchFund0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


PyTorch Fundamentals
---



In [ ]:
import torch
print(torch.__version__) # 2.6.0+cu124 >> Cuda version




2.6.0+cu124


## Introduction to tensors

### Creating tensors

Tensors are created using `torch.tensor` => https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar >> 0 dimension

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# vector >> 1 dimension

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX >> 2 dimensions

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR >> n-dimensions
TENSOR = torch.tensor([[[[[1],[2],[3]],
                        [[3],[6],[9]],
                        [[2],[4],[5]]]]])
# TENSOR = torch.tensor([[[1,2,3],
#                         [3,6,9],
#                         [2,4,5]]])
TENSOR

tensor([[[[[1],
           [2],
           [3]],

          [[3],
           [6],
           [9]],

          [[2],
           [4],
           [5]]]]])

In [ ]:
TENSOR.ndim

5

In [ ]:
TENSOR.shape # torch.Size([1, 3, 3])

torch.Size([1, 1, 3, 3, 1])

In [ ]:
TENSOR[0]

tensor([[[[1],
          [2],
          [3]],

         [[3],
          [6],
          [9]],

         [[2],
          [4],
          [5]]]])

Random Tensors


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6290, 0.7318, 0.0485, 0.8843],
        [0.2549, 0.9783, 0.0836, 0.2903],
        [0.3005, 0.6697, 0.0171, 0.9694]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with a similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels (R,G, B)
random_image_tensor

tensor([[[0.2032, 0.1433, 0.4106],
         [0.3007, 0.6551, 0.5009],
         [0.8043, 0.3463, 0.5735],
         ...,
         [0.3207, 0.7264, 0.1955],
         [0.2201, 0.7957, 0.3206],
         [0.4751, 0.1112, 0.1017]],

        [[0.0302, 0.1685, 0.9785],
         [0.7615, 0.3476, 0.0010],
         [0.2878, 0.0425, 0.8407],
         ...,
         [0.3458, 0.6963, 0.4850],
         [0.4694, 0.4040, 0.7868],
         [0.0376, 0.0025, 0.5787]],

        [[0.9697, 0.4777, 0.6849],
         [0.7452, 0.5230, 0.8111],
         [0.5052, 0.1420, 0.1051],
         ...,
         [0.1514, 0.7915, 0.7763],
         [0.7055, 0.8505, 0.9086],
         [0.7273, 0.0272, 0.9877]],

        ...,

        [[0.4024, 0.3304, 0.5629],
         [0.4985, 0.2132, 0.3056],
         [0.2998, 0.8594, 0.9209],
         ...,
         [0.7593, 0.8124, 0.3507],
         [0.3786, 0.8536, 0.1788],
         [0.0664, 0.9092, 0.6597]],

        [[0.7623, 0.4438, 0.9235],
         [0.1606, 0.5704, 0.6310],
         [0.

In [ ]:
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # torch.float32 by default

torch.float32

# Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
one_to_ten.shape
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                                                device=None,
                                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

# Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - get datatype from a tensor, can use `tensor.dtybe`
2. Tensors not right shape - get shape from a tensor, can use `tensor.shape`
1. Tensors not right device - get device from a tensor, can use `tensor.device`


In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4, dtype= torch.float16)
some_tensor

tensor([[0.1372, 0.0244, 0.0835, 0.0317],
        [0.2695, 0.3433, 0.3203, 0.8687],
        [0.7866, 0.5405, 0.3970, 0.9160]], dtype=torch.float16)

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1372, 0.0244, 0.0835, 0.0317],
        [0.2695, 0.3433, 0.3203, 0.8687],
        [0.7866, 0.5405, 0.3970, 0.9160]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating Tensors (Tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication "element-wise"
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-Wise multiplication
2. Matrix multiplication (dot product)

>> Two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` will work  -> `(2,2)`


In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,4))

tensor([[2.1289, 1.3935, 1.9107, 2.6022],
        [2.0273, 1.2896, 2.2762, 2.6661],
        [1.8422, 1.8969, 2.2576, 2.5300]])

In [ ]:
# Element wise multiplication
print(tensor,  '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplocation
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.74 ms, sys: 85 µs, total: 2.82 ms
Wall time: 2.67 ms


In [ ]:
%%time
torch.matmul(tensor, tensor) # Much faster than the for loop

CPU times: user 416 µs, sys: 0 ns, total: 416 µs
Wall time: 329 µs


tensor(14)

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B) # same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes of dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape # same information but rearranged

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape} ")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3]) 
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - requires a float as dtat type
torch.mean(x, dtype=float), x.type(torch.float32).mean()

(tensor(45., dtype=torch.float64), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the max value with argmax()
x.argmax().item()

9

In [ ]:
x[9]

tensor(90)

# Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) **vertical** or side by side (hstack) **horizontal**
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1.,10,)
x, x.shape # torch.Size([9]

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
y = x.clone()
y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changes Z changes x (because a view of tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x, x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # Number of columns doesn't change, just the rows ,, stacking rows on top of each other
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # Number of columns doesn't change, just the rows
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
random_tensor = torch.rand(2,3)
# print(random_tensor, random_tensor.shape)
x = torch.unsqueeze(random_tensor,2)
print(x, x.shape)
y = torch.squeeze(x, 0)
print(y, y.shape)
z = torch.tensor([1,2,3])
print(z, z.shape)
n = torch.unsqueeze(z,1)
n, n.shape

tensor([[[0.9328],
         [0.8320],
         [0.0527]],

        [[0.0338],
         [0.0419],
         [0.7485]]]) torch.Size([2, 3, 1])
tensor([[[0.9328],
         [0.8320],
         [0.0527]],

        [[0.0338],
         [0.0419],
         [0.7485]]]) torch.Size([2, 3, 1])
tensor([1, 2, 3]) torch.Size([3])


(tensor([[1],
         [2],
         [3]]),
 torch.Size([3, 1]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeeze = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeeze}")
print(f"\nNew shape: {x_squeeze.shape}")



Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [ ]:
st_tensor = torch.zeros(1,3,3) # first number >> number of batches, second number of rows ,, third number of columns
st_tensor, st_tensor.shape, torch.squeeze(st_tensor).shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([1, 3, 3]),
 torch.Size([3, 3]))

In [ ]:
# torch.unsquueze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")

# Add an extra dim with unsqueeze
x_unsqueeze = x_squeeze.unsqueeze(0)
print(f"New tensor : {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x = torch.randn(2,3,5)
y = torch.permute(x, (2,0,1))
x, y


x_original = torch.rand(size=(224,224,3)) # [height, width, color channels]

# Permute the original tensor to rearrange the axis or dim order
x_permuted = x_original.permute(2, 0, 1) # torch.permute(x_original, (2, 0, 1)) , shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels,  height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# dim 1 >> middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
# most inner bracket
x[0][0][0]

tensor(1)

In [ ]:
# to get number 9
x[0][2][2]

tensor(9)

In [ ]:
# You can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values from 0 and 1 dimensions but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dim but only 1 index value of 1st and 2nd dim
x[:, 1, 1]

# To get 5 without []
x[0,1,1]

tensor(5)

In [ ]:
# Get index 0 of the 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

# PyTorch tensors & Numpy
- Data in Numpy, wanted to be in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np


array = np.arange(1,8)
tensor = torch.from_numpy(array) # Warning: when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64, default tensor dtype is float32
array, tensor


(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
# Change the val of array, what will happen to the `tensor` >> tensor doesn't change and otherwise

array = array + 1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()


# Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better represntations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and pytorch >> Use  **random seed**


In [ ]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.0213, 0.7957, 0.8853, 0.6233],
        [0.1891, 0.2017, 0.2348, 0.4986],
        [0.2286, 0.9979, 0.9764, 0.9430]])
tensor([[0.0056, 0.7613, 0.8089, 0.5287],
        [0.2101, 0.2226, 0.7759, 0.3818],
        [0.6594, 0.5841, 0.5120, 0.7107]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_D)
print(random_tensor_c == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and pytorch objects on the GPUs (and making faster computations)



### 1. Getting a GPU

1. Easiest  - Use Google Colab for a free GPU.
2. Use your own GPU
3. Use cloud computing

In [1]:
!nvidia-smi

Sun May 25 15:31:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

##2. Check for GPU access with PyTorch

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [5]:
# Create a tensor (default on the cpu)
tensor = torch.tensor([1,2,3], device= 'cpu')

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU


In [7]:
# If tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with numpy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])